"""Typed scene contract for SceneSmith robot-lab exports."""

from __future__ import annotations

from dataclasses import asdict, dataclass, field
from typing import Literal

Vec3 = tuple[float, float, float]
ColorName = Literal["red", "blue", "green", "yellow", "purple", "orange"]


@dataclass(frozen=True)
class RobotLabRoom:
    """Room shell generated by SceneSmith for a robot policy eval."""

    size_m: Vec3 = (1.8, 1.4, 1.2)
    wall_rgba: tuple[float, float, float, float] = (0.72, 0.74, 0.76, 1.0)
    floor_rgba: tuple[float, float, float, float] = (0.16, 0.18, 0.20, 1.0)
    ceiling_enabled: bool = True


@dataclass(frozen=True)
class RobotLabDesk:
    """Desk fixture that supports the robot base, trays, and cubes."""

    name: str = "desk"
    center_m: Vec3 = (0.25, 0.0, 0.28)
    size_m: Vec3 = (0.84, 0.56, 0.06)
    rgba: tuple[float, float, float, float] = (0.54, 0.50, 0.44, 1.0)


@dataclass(frozen=True)
class RobotLabRobot:
    """Robot digital twin mount and control contract."""

    name: str = "so101"
    model: str = "SO-101"
    base_position_m: Vec3 = (-0.06, 0.0, 0.33)
    joint_names: tuple[str, ...] = (
        "shoulder_pan",
        "shoulder_lift",
        "elbow_flex",
        "wrist_flex",
        "wrist_roll",
        "gripper",
    )
    urdf_joint_names: tuple[str, ...] = (
        "Rotation",
        "Pitch",
        "Elbow",
        "Wrist_Pitch",
        "Wrist_Roll",
        "Jaw",
    )
    joint_name_map: tuple[tuple[str, str], ...] = (
        ("shoulder_pan", "Rotation"),
        ("shoulder_lift", "Pitch"),
        ("elbow_flex", "Elbow"),
        ("wrist_flex", "Wrist_Pitch"),
        ("wrist_roll", "Wrist_Roll"),
        ("gripper", "Jaw"),
    )
    joint_position_units: tuple[str, ...] = (
        "radian",
        "radian",
        "radian",
        "radian",
        "radian",
        "radian",
    )
    default_urdf_joint_positions_rad: tuple[tuple[str, float], ...] = (
        ("Rotation", 0.0),
        ("Pitch", -0.55),
        ("Elbow", 1.05),
        ("Wrist_Pitch", -0.48),
        ("Wrist_Roll", 0.0),
        ("Jaw", 0.35),
    )
    source_mjcf: str = "external/SO-ARM100/Simulation/SO101/so101_new_calib.xml"
    source_urdf: str = (
        "external/leLab/frontend/public/so-101-urdf/urdf/so101_new_calib.urdf"
    )


@dataclass(frozen=True)
class RobotLabTray:
    """Colored sorting target."""

    name: str
    color: ColorName
    center_m: Vec3
    size_m: Vec3 = (0.18, 0.12, 0.012)


@dataclass(frozen=True)
class RobotLabCube:
    """Free-body manipuland used by the robot policy."""

    name: str
    color: ColorName
    initial_position_m: Vec3
    side_length_m: float = 0.032
    mass_kg: float = 0.035


@dataclass(frozen=True)
class RobotLabFiducial:
    """Fixed workspace fiducial for camera/world calibration."""

    name: str = "apriltag_0"
    family: str = "tag36h11"
    tag_id: int = 0
    size_m: float = 0.075
    position_m: Vec3 = (0.08, 0.235, 0.313)
    euler_deg: Vec3 = (0.0, 0.0, 0.0)
    attached_to: str = "desk_top"
    role: str = "world_frame_anchor"
    # Canonical tag36h11 ID 0 at total_width=10. A "1" renders black.
    grid: tuple[str, ...] = (
        "0000000000",
        "0111111110",
        "0100101010",
        "0110001010",
        "0110011110",
        "0101011110",
        "0110100110",
        "0111101110",
        "0111111110",
        "0000000000",
    )


@dataclass(frozen=True)
class RobotLabPolicy:
    """LeRobot/LeLab policy-facing metadata."""

    provider: str = "molmoact2"
    repo_id: str = "lerobot/MolmoAct2-SO100_101-LeRobot"
    action_server_env: str = "MOLMOACT2_ACTION_SERVER_URL"
    task: str = (
        "Sort each cube into the same-colored tray: red cubes into the red tray "
        "and blue cubes into the blue tray."
    )


@dataclass(frozen=True)
class RobotLabScene:
    """Complete SceneSmith robot-lab scene contract."""

    schema_version: str
    scene_id: str
    description: str
    room: RobotLabRoom
    desk: RobotLabDesk
    robot: RobotLabRobot
    trays: tuple[RobotLabTray, ...]
    cubes: tuple[RobotLabCube, ...]
    policy: RobotLabPolicy
    fiducials: tuple[RobotLabFiducial, ...] = field(default_factory=tuple)
    success_metric: str = "all_cubes_inside_matching_color_trays"
    source: dict[str, str] = field(default_factory=dict)

    def to_dict(self) -> dict:
        return asdict(self)


def tuple3(values: list[float] | tuple[float, ...], field_name: str) -> Vec3:
    if len(values) != 3:
        raise ValueError(f"{field_name} must contain exactly three numbers")
    return (float(values[0]), float(values[1]), float(values[2]))


def tuple4(
    values: list[float] | tuple[float, ...],
    field_name: str,
) -> tuple[float, float, float, float]:
    if len(values) != 4:
        raise ValueError(f"{field_name} must contain exactly four numbers")
    return (float(values[0]), float(values[1]), float(values[2]), float(values[3]))


def scene_from_dict(payload: dict) -> RobotLabScene:
    """Rehydrate a `RobotLabScene` from `scene.to_dict()` JSON."""

    return RobotLabScene(
        schema_version=str(payload["schema_version"]),
        scene_id=str(payload["scene_id"]),
        description=str(payload["description"]),
        room=RobotLabRoom(
            size_m=tuple3(payload["room"].get("size_m", RobotLabRoom.size_m), "room.size_m"),
            wall_rgba=tuple4(
                payload["room"].get("wall_rgba", RobotLabRoom.wall_rgba),
                "room.wall_rgba",
            ),
            floor_rgba=tuple4(
                payload["room"].get("floor_rgba", RobotLabRoom.floor_rgba),
                "room.floor_rgba",
            ),
            ceiling_enabled=bool(payload["room"].get("ceiling_enabled", True)),
        ),
        desk=RobotLabDesk(
            name=str(payload["desk"].get("name", "desk")),
            center_m=tuple3(payload["desk"]["center_m"], "desk.center_m"),
            size_m=tuple3(payload["desk"]["size_m"], "desk.size_m"),
            rgba=tuple4(payload["desk"].get("rgba", RobotLabDesk.rgba), "desk.rgba"),
        ),
        robot=RobotLabRobot(
            name=str(payload["robot"].get("name", "so101")),
            model=str(payload["robot"].get("model", "SO-101")),
            base_position_m=tuple3(payload["robot"]["base_position_m"], "robot.base_position_m"),
            joint_names=tuple(payload["robot"].get("joint_names", RobotLabRobot.joint_names)),
            urdf_joint_names=tuple(
                payload["robot"].get("urdf_joint_names", RobotLabRobot.urdf_joint_names)
            ),
            joint_name_map=tuple(
                tuple(item)
                for item in payload["robot"].get("joint_name_map", RobotLabRobot.joint_name_map)
            ),
            joint_position_units=tuple(
                payload["robot"].get(
                    "joint_position_units",
                    RobotLabRobot.joint_position_units,
                )
            ),
            default_urdf_joint_positions_rad=tuple(
                tuple(item)
                for item in payload["robot"].get(
                    "default_urdf_joint_positions_rad",
                    RobotLabRobot.default_urdf_joint_positions_rad,
                )
            ),
            source_mjcf=str(payload["robot"].get("source_mjcf", RobotLabRobot.source_mjcf)),
            source_urdf=str(payload["robot"].get("source_urdf", RobotLabRobot.source_urdf)),
        ),
        trays=tuple(
            RobotLabTray(
                name=str(tray["name"]),
                color=tray["color"],
                center_m=tuple3(tray["center_m"], f"{tray['name']}.center_m"),
                size_m=tuple3(tray.get("size_m", RobotLabTray.size_m), f"{tray['name']}.size_m"),
            )
            for tray in payload["trays"]
        ),
        cubes=tuple(
            RobotLabCube(
                name=str(cube["name"]),
                color=cube["color"],
                initial_position_m=tuple3(
                    cube["initial_position_m"],
                    f"{cube['name']}.initial_position_m",
                ),
                side_length_m=float(cube.get("side_length_m", RobotLabCube.side_length_m)),
                mass_kg=float(cube.get("mass_kg", RobotLabCube.mass_kg)),
            )
            for cube in payload["cubes"]
        ),
        policy=RobotLabPolicy(
            provider=str(payload["policy"].get("provider", RobotLabPolicy.provider)),
            repo_id=str(payload["policy"].get("repo_id", RobotLabPolicy.repo_id)),
            action_server_env=str(
                payload["policy"].get(
                    "action_server_env",
                    RobotLabPolicy.action_server_env,
                )
            ),
            task=str(payload["policy"].get("task", RobotLabPolicy.task)),
        ),
        fiducials=tuple(
            RobotLabFiducial(
                name=str(fiducial.get("name", "apriltag_0")),
                family=str(fiducial.get("family", "tag36h11")),
                tag_id=int(fiducial.get("tag_id", 0)),
                size_m=float(fiducial.get("size_m", 0.075)),
                position_m=tuple3(fiducial["position_m"], f"{fiducial['name']}.position_m"),
                euler_deg=tuple3(fiducial.get("euler_deg", (0, 0, 0)), f"{fiducial['name']}.euler_deg"),
                attached_to=str(fiducial.get("attached_to", "desk_top")),
                role=str(fiducial.get("role", "world_frame_anchor")),
                grid=tuple(fiducial.get("grid", RobotLabFiducial.grid)),
            )
            for fiducial in payload.get("fiducials", ())
        ),
        success_metric=str(
            payload.get("success_metric", "all_cubes_inside_matching_color_trays")
        ),
        source=dict(payload.get("source", {})),
    )
